// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Marwan Mohamed Zein's professional profile summary, focus areas, and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "Marwan Mohamed Zein",
            handle: "Martell0x1",
            title: "Full Stack Developer",
            focus: ["Backend", "Embedded", "IoT", "Linux / Systems Programming"],
            stack: ["Angular", ".NET", "Node.js", "NestJS", "Rust"],
            location: "Alexandria, Egypt",
            education: "B.Sc. Computer Science, Alexandria University (expected May 2027)",
            currentRole: "Backend Engineering Intern @ Dice Marketing (Spread Social)",
            website: "https://martell0x1.lovable.app",
            github: "https://github.com/Martell0x1",
            youtube: "https://www.youtube.com/@marawanmohamed7126",
            email: "marawanzein222@gmail.com"
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var PROJECTS = [
  {
    name: "Monitex",
    description: "IoT monitoring & anomaly detection platform (ASP.NET Core, Rust/ESP32, RabbitMQ, Angular).",
    tags: ["ASP.NET Core", "Rust", "ESP32", "RabbitMQ", "Angular"],
    url: "https://github.com/Martell0x1/Monitex"
  },
  {
    name: "VisionGate",
    description: "Smart garage access control with license-plate recognition (NestJS, Flutter, ESP32, YOLO/OpenCV).",
    tags: ["NestJS", "Flutter", "ESP32", "YOLO", "OpenCV"],
    url: "https://github.com/Martell0x1/VisionGate"
  },
  {
    name: "Rusty-x86_64",
    description: "Bare-metal x86_64 OS kernel written in Rust, tested on QEMU.",
    tags: ["Rust", "x86_64", "QEMU", "OS"],
    url: "https://github.com/Martell0x1/Rusty-x86_64"
  },
  {
    name: "FileShare",
    description: "Cloud file sharing service on AWS (Node.js, S3, EC2, IAM).",
    tags: ["Node.js", "AWS", "S3", "EC2"],
    url: "https://github.com/Martell0x1"
  }
];
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "List Marwan's featured projects with descriptions, tech tags, and repository URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PROJECTS, null, 2) }],
    structuredContent: { projects: PROJECTS }
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var SKILLS = {
  languages: ["C++", "Java", "Python", "JavaScript/Node.js", "Rust", "PHP"],
  frameworks: ["Laravel", "NestJS", "Express", "Angular", ".NET / ASP.NET Core"],
  data: ["PostgreSQL", "MySQL", "MongoDB", "Redis"],
  infra: ["Kafka", "RabbitMQ", "Docker", "AWS", "Azure", "Linux"]
};
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills",
  description: "List Marwan's technical skills grouped by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SKILLS, null, 2) }],
    structuredContent: SKILLS
  })
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var EXPERIENCE = [
  {
    role: "Backend Engineering Intern",
    company: "Dice Marketing (Spread Social)",
    from: "May 2026",
    to: "Present",
    highlights: [
      "Built REST APIs and event-driven workflows for the Spread Social platform."
    ]
  },
  {
    role: "Coding Instructor",
    company: "ElCode - FCDS, Alexandria University",
    highlights: ["Taught programming fundamentals and problem solving."]
  }
];
var list_experience_default = defineTool4({
  name: "list_experience",
  title: "List experience",
  description: "List Marwan's work experience and teaching roles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(EXPERIENCE, null, 2) }],
    structuredContent: { experience: EXPERIENCE }
  })
});

// src/lib/mcp/tools/get-page-views.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_page_views_default = defineTool5({
  name: "get_page_views",
  title: "Get portfolio page views",
  description: "Return the total number of views the portfolio home page has received.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async () => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured" }], isError: true };
    }
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("page_views").select("view_count, page_name").eq("page_name", "home").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const views = data?.view_count ?? 0;
    return {
      content: [{ type: "text", text: `Portfolio has ${views} total page views.` }],
      structuredContent: { views }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "martell0x1-portfolio-mcp",
  title: "Marwan Zein Portfolio MCP",
  version: "0.1.0",
  instructions: "Read-only tools exposing Marwan Mohamed Zein's (Martell0x1) portfolio: profile, projects, skills, experience, and page view count. Use `get_profile` first for an overview.",
  tools: [get_profile_default, list_projects_default, list_skills_default, list_experience_default, get_page_views_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
